### ISSUE TITLE
Can i send a String to the javascript code or call a react native function when an image target is pressed in the AR View?

### ISSUE THREAD

**Issue by indranil316** [joaquinlom/react-native-wikitude-sdk#7]
I want to send a string ( user id ) to the javascript code and use it there while fetching the json from server.
or If i can call a react native function when i press image targets in the AR, that would be great too.
Is there a way?

**Comment by joaquinlom** [comment]
to have bi-directional communication, you can use the callJavascript method(from React) and the ar.platform.sendJSONObject from the experience ( use the event from React to catch this json)

**Comment by indranil316** [comment]
Thanks it worked.

**Comment by GianlucaP99** [comment]
Hi,
is there an example of passing values ​​from React to javascript and from javascript to React?
- I only found the javascritp -> React. (Example in react-native-wikitude-sdk-example, exercise number 10_BrowsingPois_5_NativeDetailScreen. (Partial, but clear)
- for the React -> javascript I didn't find any... there is some documentation written in react-native-wikitude-sdk-example exercise number 09_ObtainPoiData_1_FromApplicationModel, but it's not very clear to me. I understood to have to put the attribute callJavascript inside <WikitudeView />, but it is not clear to me in what format... an example would help, moreover it is not clear to me from javascript how to receive this JSON file because it is written to call 'architectView.callJavaScript ()', but I'm not clear what architectView is.

Many thanks in advance.

**Comment by joaquinlom** [comment]
Hi.
to pass data to the Wikitude Experience , you need to call the method callJavascript from the WikitudeView component(that would ve the architectView reference).
this string it would be as open console and put the js inside , is like a eval function.

and to pass data from the experience (Javascript) to react, you need to listen onJSONReceived event (react) and call  the ar.platform.sendJSONObject in the Javascript experience.

**Comment by GianlucaP99** [comment]
Hi,
grazie mille per le dritte ora mi è più chiaro, ma dato che sono nuovo su react non mi è chiarissimo come mai dentro useEffect la ref a wikitudeview mi rimanga null....
code : https://pastebin.pl/view/47c86871

**Comment by GianlucaP99** [comment]
Hi,
thank you very much for the tips now it is clearer to me, but since I am new to react it is not very clear to me why inside useEffect the ref a wikitudeview I remain null....
code : https://pastebin.pl/view/47c86871

**Comment by joaquinlom** [comment]
Hi.
I recommend fire callJavascript inside the event onFinishLoading.

the lifecycle is still kinda weird because how React Native link the Native View.
maybe you can add a state flag and flip it inside the onFinishLoading, then call the javascript method

**Comment by GianlucaP99** [comment]
perfect, thank you very much
